M48
; DRILL file {KiCad 9.0.6} date 2025-12-31T13:17:51-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-31T13:17:51-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X48.0Y94.55
T2
X34.0Y96.3
X34.0Y89.3
T3
X3.0Y97.0
X3.0Y3.0
X87.0Y97.0
X87.0Y3.0
T1
G00X42.125Y94.55
M15
G01X41.875Y94.55
M16
G05
M30
